# Generated by Django 3.0.2 on 2020-01-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rhandler', '0003_auto_20200121_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rhandler.UserInfo'),
        ),
    ]
