# Generated by Django 3.0.2 on 2020-01-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rhandler', '0005_auto_20200121_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
