# Generated by Django 3.0.2 on 2020-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhandler', '0006_remove_userinfo_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageFromDevice',
        ),
        migrations.AlterField(
            model_name='client',
            name='numberID',
            field=models.CharField(max_length=5),
        ),
    ]
