# Generated by Django 3.0.2 on 2020-02-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhandler', '0007_auto_20200126_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='configs',
            field=models.TextField(default=''),
        ),
    ]
